#ifndef AVOIDANCE_INTRUDER_HPP
#define AVOIDANCE_INTRUDER_HPP

#include <string>

class Avoidance_intruder
{
public:
    Avoidance_intruder(std::string ac_id, double latd,
                       double lond, double alt, double hdg,
                       double gs, double recorded_time);

    std::string getAircraftId();
    double getReceivedTime();

    void setData(double latd, double lond,
                 double alt, double hdg,
                 double gs, double recorded_time);
private:
    // returns timestamp in seconds
    double getTimeStamp();

    // parameters from data package
    std::string _aircaft_id;
    double _latd;
    double _lond;
    double _alt;
    double _heading;
    double _groundspeed;
    double _recorded_time;

    // data to be generated by avoidance computer
    double _received_time;
};

#endif // AVOIDANCE_INTRUDER_HPP
